name: Update Profile Summary Cards

on:
  workflow_dispatch:
  schedule:
    - cron: "23 3 * * 0"

permissions:
  contents: write

jobs:
  profile-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Generate profile summary cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.CLOC_PAT }}
        with:
          USERNAME: YokaMakuto
          BRANCH_NAME: main
          UTC_OFFSET: 1
          THEME: github_dark
          AUTO_PUSH: true
